spring:
  application:
    name: newscuss-be
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  session:
    timeout: 30m
  servlet:
    encoding:
      charset: UTF-8
      force: true

server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force: true

python:
  api:
    base-url: ${PYTHON_API_URL:http://localhost:5000/api}

rest:
  timeout:
    connect: 5000
    read: 60000

logging:
  level:
    root: INFO
    com.example.newscussbe: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"